.. |response:list| replace:: In successful, this method returns a 200 status
   and a list of objects in the response body.

.. |response:create| replace:: If successful, this method returns a 201 status,
   the URI of the newly created object in the Location-header
   and an partial object in the response body.

.. |response:read| replace:: If successful, this method returns a 200 status
   and an object in the response body.

.. |response:update| replace:: If successful, this method returns a 200 or 204 status.

.. |response:delete| replace:: If successful, this method returns a 200 or 204 status.
