.. |request:list| replace:: Do not supply a request body with this method.

.. |response:list| replace:: In successful, this method returns a 200 status
   and a list of objects in the response body.

.. |response:display| replace:: If successful, this method returns a 200 status
   and an object in the response body.

.. |request:create| replace:: Supply an object in the request body.

.. |response:create| replace:: If successful, this method returns a 201 status,
   the URI of the newly created object in the Location-header
   and an partial object in the response body.

.. |request:read| replace:: Do not supply a request body with this method.

.. |response:read| replace:: If successful, this method returns a 200 status
   and an object in the response body.

.. |request:update| replace:: Supply an (partial) object.

.. |response:update| replace:: If successful, this method returns a 200 or 204 status.

.. |request:delete| replace:: Do not supply a request body with this method.

.. |response:delete| replace:: If successful, this method returns a 200 or 204 status.
