EngelsystemApiResourceBundle_event_get:
    pattern:   /api/v1/resource/event
    defaults:  { _controller: EngelsystemApiResourceBundle:Event:get, _format: json }
    requirements:
        _method: GET

EngelsystemApiResourceBundle_room_list:
    pattern:   /api/v1/resource/room
    defaults:  { _controller: EngelsystemApiResourceBundle:Room:list, _format: json }
    requirements:
        _method: GET
        _format: JSON

EngelsystemApiResourceBundle_room_create:
    pattern:   /api/v1/resource/room
    defaults:  { _controller: EngelsystemApiResourceBundle:Room:create, _format: json }
    requirements:
        _method: POST
        _format: JSON

EngelsystemApiResourceBundle_room_read:
    pattern:   /api/v1/resource/room/{id}
    defaults:  { _controller: EngelsystemApiResourceBundle:Room:read, _format: json }
    requirements:
        _method: GET
        _format: JSON

EngelsystemApiResourceBundle_room_update:
    pattern:   /api/v1/resource/room/{id}
    defaults:  { _controller: EngelsystemApiResourceBundle:Room:update, _format: json }
    requirements:
        _method: PUT
        _format: JSON

EngelsystemApiResourceBundle_room_delete:
    pattern:   /api/v1/resource/room/{id}
    defaults:  { _controller: EngelsystemApiResourceBundle:Room:delete, _format: json }
    requirements:
        _method: DELETE
        _format: JSON

EngelsystemApiResourceBundle_shift_list:
    pattern:   /api/v1/resource/shift
    defaults:  { _controller: EngelsystemApiResourceBundle:Shift:list }
    requirements:
        _method: GET

EngelsystemApiResourceBundle_shift_create:
    pattern:   /api/v1/resource/shift
    defaults:  { _controller: EngelsystemApiResourceBundle:Shift:create }
    requirements:
        _method: POST

EngelsystemApiResourceBundle_shift_read:
    pattern:   /api/v1/resource/shift/{id}
    defaults:  { _controller: EngelsystemApiResourceBundle:Shift:read }
    requirements:
        _method: GET

EngelsystemApiResourceBundle_shift_update:
    pattern:   /api/v1/resource/shift/{id}
    defaults:  { _controller: EngelsystemApiResourceBundle:Shift:update }
    requirements:
        _method: PUT

EngelsystemApiResourceBundle_shift_delete:
    pattern:   /api/v1/resource/shift/{id}
    defaults:  { _controller: EngelsystemApiResourceBundle:Shift:delete }
    requirements:
        _method: DELETE

EngelsystemApiResourceBundle_shifttask_list:
    pattern:   /api/v1/resource/shift/{shift_id}/task
    defaults:  { _controller: EngelsystemApiResourceBundle:ShiftTask:list }
    requirements:
        _method: GET

EngelsystemApiResourceBundle_shifttask_create:
    pattern:   /api/v1/resource/shift/{shift_id}/task/{type_id}
    defaults:  { _controller: EngelsystemApiResourceBundle:ShiftTask:create }
    requirements:
        _method: POST

EngelsystemApiResourceBundle_shift_update:
    pattern:   /api/v1/resource/shift/{shift_id}/task/{type_id}/{task_id}
    defaults:  { _controller: EngelsystemApiResourceBundle:Shift:update }
    requirements:
        _method: PUT

EngelsystemApiResourceBundle_shift_delete:
    pattern:   /api/v1/resource/shift/{shift_id}/task/{type_id}/{task_id}
    defaults:  { _controller: EngelsystemApiResourceBundle:Shift:delete }
    requirements:
        _method: DELETE

EngelsystemApiResourceBundle_shift_delete_all:
    pattern:   /api/v1/resource/shift/{shift_id}/task
    defaults:  { _controller: EngelsystemApiResourceBundle:Shift:deleteAll }
    requirements:
        _method: DELETE

EngelsystemApiResourceBundle_type_list:
    pattern:   /api/v1/resource/type
    defaults:  { _controller: EngelsystemApiResourceBundle:Type:list }
    requirements:
        _method: GET

EngelsystemApiResourceBundle_type_create:
    pattern:   /api/v1/resource/type
    defaults:  { _controller: EngelsystemApiResourceBundle:Type:create }
    requirements:
        _method: POST

EngelsystemApiResourceBundle_type_read:
    pattern:   /api/v1/resource/type/{id}
    defaults:  { _controller: EngelsystemApiResourceBundle:Type:read }
    requirements:
        _method: GET

EngelsystemApiResourceBundle_type_update:
    pattern:   /api/v1/resource/type/{id}
    defaults:  { _controller: EngelsystemApiResourceBundle:Type:update }
    requirements:
        _method: PUT

EngelsystemApiResourceBundle_type_delete:
    pattern:   /api/v1/resource/type/{id}
    defaults:  { _controller: EngelsystemApiResourceBundle:Type:delete }
    requirements:
        _method: DELETE

