parameters:
#    engelsystem_resource.example.class: Engelsystem\ApiResourceBundle\Example

services:
#    engelsystem_resource.example:
#        class: %engelsystem_resource.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
