EngelsystemResourceBundle_event_get:
    pattern:   /api/v1/resource/event
    defaults:  { _controller: EngelsystemResourceBundle:Event:get }
    requirements:
        _method: GET

EngelsystemResourceBundle_room_list:
    pattern:   /api/v1/resource/room
    defaults:  { _controller: EngelsystemResourceBundle:Room:list }
    requirements:
        _method: GET

EngelsystemResourceBundle_room_create:
    pattern:   /api/v1/resource/room
    defaults:  { _controller: EngelsystemResourceBundle:Room:create }
    requirements:
        _method: POST

EngelsystemResourceBundle_room_read:
    pattern:   /api/v1/resource/room/{id}
    defaults:  { _controller: EngelsystemResourceBundle:Room:read }
    requirements:
        _method: GET

EngelsystemResourceBundle_room_update:
    pattern:   /api/v1/resource/room/{id}
    defaults:  { _controller: EngelsystemResourceBundle:Room:update }
    requirements:
        _method: PUT

EngelsystemResourceBundle_room_delete:
    pattern:   /api/v1/resource/room/{id}
    defaults:  { _controller: EngelsystemResourceBundle:Room:delete }
    requirements:
        _method: DELETE

EngelsystemResourceBundle_shift_list:
    pattern:   /api/v1/resource/shift
    defaults:  { _controller: EngelsystemResourceBundle:Shift:list }
    requirements:
        _method: GET

EngelsystemResourceBundle_shift_create:
    pattern:   /api/v1/resource/shift
    defaults:  { _controller: EngelsystemResourceBundle:Shift:create }
    requirements:
        _method: POST

EngelsystemResourceBundle_shift_read:
    pattern:   /api/v1/resource/shift/{id}
    defaults:  { _controller: EngelsystemResourceBundle:Shift:read }
    requirements:
        _method: GET

EngelsystemResourceBundle_shift_update:
    pattern:   /api/v1/resource/shift/{id}
    defaults:  { _controller: EngelsystemResourceBundle:Shift:update }
    requirements:
        _method: PUT

EngelsystemResourceBundle_shift_delete:
    pattern:   /api/v1/resource/shift/{id}
    defaults:  { _controller: EngelsystemResourceBundle:Shift:delete }
    requirements:
        _method: DELETE

EngelsystemResourceBundle_shifttask_list:
    pattern:   /api/v1/resource/shift/{shift_id}/task
    defaults:  { _controller: EngelsystemResourceBundle:ShiftTask:list }
    requirements:
        _method: GET

EngelsystemResourceBundle_shifttask_create:
    pattern:   /api/v1/resource/shift/{shift_id}/task/{type_id}
    defaults:  { _controller: EngelsystemResourceBundle:ShiftTask:create }
    requirements:
        _method: POST

EngelsystemResourceBundle_shift_update:
    pattern:   /api/v1/resource/shift/{shift_id}/task/{type_id}/{task_id}
    defaults:  { _controller: EngelsystemResourceBundle:Shift:update }
    requirements:
        _method: PUT

EngelsystemResourceBundle_shift_delete:
    pattern:   /api/v1/resource/shift/{shift_id}/task/{type_id}/{task_id}
    defaults:  { _controller: EngelsystemResourceBundle:Shift:delete }
    requirements:
        _method: DELETE

EngelsystemResourceBundle_shift_delete_all:
    pattern:   /api/v1/resource/shift/{shift_id}/task
    defaults:  { _controller: EngelsystemResourceBundle:Shift:deleteAll }
    requirements:
        _method: DELETE

EngelsystemResourceBundle_type_list:
    pattern:   /api/v1/resource/type
    defaults:  { _controller: EngelsystemResourceBundle:Type:list }
    requirements:
        _method: GET

EngelsystemResourceBundle_type_create:
    pattern:   /api/v1/resource/type
    defaults:  { _controller: EngelsystemResourceBundle:Type:create }
    requirements:
        _method: POST

EngelsystemResourceBundle_type_read:
    pattern:   /api/v1/resource/type/{id}
    defaults:  { _controller: EngelsystemResourceBundle:Type:read }
    requirements:
        _method: GET

EngelsystemResourceBundle_type_update:
    pattern:   /api/v1/resource/type/{id}
    defaults:  { _controller: EngelsystemResourceBundle:Type:update }
    requirements:
        _method: PUT

EngelsystemResourceBundle_type_delete:
    pattern:   /api/v1/resource/type/{id}
    defaults:  { _controller: EngelsystemResourceBundle:Type:delete }
    requirements:
        _method: DELETE

